name: Run unit tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.3'
      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./...